### ISSUE TITLE
Port CanOpenNode to support HAL

### ISSUE THREAD

**Issue by Fszta** [w1ne/CANOpenNode-CubeMX-HAL#1]
Hello Andrii, i need to work with canopen library for a robotic application, unfortunately the main part of the project has been developped using HAL library and i don't have enough time to make CanOpenNode HAL compatible, do you succeed in this task?

**Comment by w1ne** [comment]
Hi Fszta, 
you can use driver at my repo, it is working fine but not excessively tested. I did not notice any problems with SDO/PDO transmission. 
Some limitations:
1. You need to configure CAN using CubeMX, code assumed "hcan1" handler. I will make it configurable later. But for now it is like it is.
3. No CAN hardware filters at the moment.
2. There is no EEPROM driver. I am using proprietary library and wrapper around EEPROM driver from the CANOpen stack. So you will need to adapt EEPROM driver for your needs.  

Otherwise it is working perfectly fine.
If you need working example project in CubeMX for Atollic Studio tested with STM32L431, I can share it. just let me know. 

Regards,
Andrii

**Comment by Fszta** [comment]
Effectively it's perfect for my needs, i have a look to the full code, i'll try it today. Yes a working example could be very helpful! Thanks for your explanations

**Comment by w1ne** [comment]
I have added a working example. It has been tested on the STM32L452 Nucleo board. CubeMX project is included.
